export const BOARD_CREATE_REQUEST = 'BOARD_CREATE_REQUEST'
export const BOARD_CREATE_SUCCESS = 'BOARD_CREATE_SUCCESS'
export const BOARD_CREATE_FAIL = 'BOARD_CREATE_FAIL'
export const BOARD_CREATE_RESET = 'BOARD_CREATE_RESET'

export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST'
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS'
export const BOARD_LIST_FAIL = 'BOARD_LIST_FAIL'

export const BOARD_TO_EDIT_REQUEST = 'BOARD_TO_EDIT_REQUEST'
export const BOARD_TO_EDIT_SUCCESS = 'BOARD_TO_EDIT_SUCCESS'
export const BOARD_TO_EDIT_FAIL = 'BOARD_TO_EDIT_FAIL'
export const BOARD_TO_EDIT_RESET = 'BOARD_TO_EDIT_RESET'
export const BOARD_SHOW_EDIT = 'BOARD_SHOW_EDIT'

export const BOARD_TO_EDIT_CLASSES_REQUEST = 'BOARD_TO_EDIT_CLASSES_REQUEST'
export const BOARD_TO_EDIT_CLASSES_SUCCESS = 'BOARD_TO_EDIT_CLASSES_SUCCESS'
export const BOARD_TO_EDIT_CLASSES_FAIL = 'BOARD_TO_EDIT_CLASSES_FAIL'

export const BOARD_DELETE_CLASS_REQUEST = 'BOARD_DELETE_CLASS_REQUEST'
export const BOARD_DELETE_CLASS_SUCCESS = 'BOARD_DELETE_CLASS_SUCCESS'
export const BOARD_DELETE_CLASS_FAIL = 'BOARD_DELETE_CLASS_FAIL'

export const CLASS_TO_DELETE_REQUEST = 'CLASS_TO_DELETE_REQUEST'
export const CLASS_TO_DELETE_SUCCESS = 'CLASS_TO_DELETE_SUCCESS'
export const CLASS_TO_DELETE_FAIL = 'CLASS_TO_DELETE_FAIL'

export const BOARD_UPDATE_REQUEST = 'BOARD_UPDATE_REQUEST'
export const BOARD_UPDATE_SUCCESS = 'BOARD_UPDATE_SUCCESS'
export const BOARD_UPDATE_FAIL = 'BOARD_UPDATE_FAIL'

export const BOARD_DELETE_REQUEST = 'BOARD_DELETE_REQUEST'
export const BOARD_DELETE_SUCCESS = 'BOARD_DELETE_SUCCESS'
export const BOARD_DELETE_FAIL = 'BOARD_DELETE_FAIL'

export const BOARD_VIEW_REQUEST = 'BOARD_VIEW_REQUEST'
export const BOARD_VIEW_SUCCESS = 'BOARD_VIEW_SUCCESS'
export const BOARD_VIEW_FAIL = 'BOARD_VIEW_FAIL'