export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'

export const MONDAY_TASKS_REQUEST = 'MONDAY_TASKS_REQUEST'
export const MONDAY_TASKS_SUCCESS = 'MONDAY_TASKS_SUCCESS'
export const MONDAY_TASKS_FAIL = 'MONDAY_TASKS_FAIL'

export const TUESDAY_TASKS_REQUEST = 'TUESDAY_TASKS_REQUEST'
export const TUESDAY_TASKS_SUCCESS = 'TUESDAY_TASKS_SUCCESS'
export const TUESDAY_TASKS_FAIL = 'TUESDAY_TASKS_FAIL'

export const WEDNESDAY_TASKS_REQUEST = 'WEDNESDAY_TASKS_REQUEST'
export const WEDNESDAY_TASKS_SUCCESS = 'WEDNESDAY_TASKS_SUCCESS'
export const WEDNESDAY_TASKS_FAIL = 'WEDNESDAY_TASKS_FAIL'

export const THURSDAY_TASKS_REQUEST = 'THURSDAY_TASKS_REQUEST'
export const THURSDAY_TASKS_SUCCESS = 'THURSDAY_TASKS_SUCCESS'
export const THURSDAY_TASKS_FAIL = 'THURSDAY_TASKS_FAIL'

export const FRIDAY_TASKS_REQUEST = 'FRIDAY_TASKS_REQUEST'
export const FRIDAY_TASKS_SUCCESS = 'FRIDAY_TASKS_SUCCESS'
export const FRIDAY_TASKS_FAIL = 'FRIDAY_TASKS_FAIL'

export const SATURDAY_TASKS_REQUEST = 'SATURDAY_TASKS_REQUEST'
export const SATURDAY_TASKS_SUCCESS = 'SATURDAY_TASKS_SUCCESS'
export const SATURDAY_TASKS_FAIL = 'SATURDAY_TASKS_FAIL'

export const SUNDAY_TASKS_REQUEST = 'SUNDAY_TASKS_REQUEST'
export const SUNDAY_TASKS_SUCCESS = 'SUNDAY_TASKS_SUCCESS'
export const SUNDAY_TASKS_FAIL = 'SUNDAY_TASKS_FAIL'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'

export const TASK_TO_EDIT_REQUEST = 'TASK_TO_EDIT_REQUEST'
export const TASK_TO_EDIT_SUCCESS = 'TASK_TO_EDIT_SUCCESS'
export const TASK_TO_EDIT_FAIL = 'TASK_TO_EDIT_FAIL'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'

export const TASK_COMPLETE_REQUEST = 'TASK_COMPLETE_REQUEST'
export const TASK_COMPLETE_SUCCESS = 'TASK_COMPLETE_SUCCESS'
export const TASK_COMPLETE_FAIL = 'TASK_COMPLETE_FAIL'