export const WEEK_LIST_REQUEST = 'WEEK_LIST_REQUEST'
export const WEEK_LIST_SUCCESS = 'WEEK_LIST_SUCCESS'
export const WEEK_LIST_FAIL = 'WEEK_LIST_FAIL'

export const WEEK_ADD_REQUEST = 'WEEK_ADD_REQUEST'
export const WEEK_ADD_SUCCESS = 'WEEK_ADD_SUCCESS'
export const WEEK_ADD_FAIL = 'WEEK_ADD_FAIL'

export const WEEK_TO_EDIT_REQUEST = 'WEEK_TO_EDIT_REQUEST'
export const WEEK_TO_EDIT_SUCCESS = 'WEEK_TO_EDIT_SUCCESS'
export const WEEK_TO_EDIT_FAIL = 'WEEK_TO_EDIT_FAIL'
export const WEEK_TO_EDIT_RESET = 'WEEK_TO_EDIT_RESET'

export const WEEK_DELETE_REQUEST = 'WEEK_DELETE_REQUEST'
export const WEEK_DELETE_SUCCESS = 'WEEK_DELETE_SUCCESS'
export const WEEK_DELETE_FAIL = 'WEEK_DELETE_FAIL'

export const WEEK_UPDATE_REQUEST = 'WEEK_UPDATE_REQUEST'
export const WEEK_UPDATE_SUCCESS = 'WEEK_UPDATE_SUCCESS'
export const WEEK_UPDATE_FAIL = 'WEEK_UPDATE_FAIL'

export const WEEK_VIEW_REQUEST = 'WEEK_VIEW_REQUEST'
export const WEEK_VIEW_SUCCESS = 'WEEK_VIEW_SUCCESS'
export const WEEK_VIEW_FAIL = 'WEEK_VIEW_FAIL'

export const WEEK_DAYS = 'WEEK_DAYS'

export const WEEK_CLASSES_REQUEST = 'WEEK_CLASSES_REQUEST'
export const WEEK_CLASSES_SUCCESS = 'WEEK_CLASSES_SUCCESS'
export const WEEK_CLASSES_FAIL = 'WEEK_CLASSES_FAIL'