# Generated by Django 3.2.5 on 2021-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_classname_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created',
        ),
        migrations.AddField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
